# fly.toml app configuration file for fueldao-offchain-server

app = "fueldao-offchain-server"
primary_region = "sin"
kill_signal = "SIGINT"
kill_timeout = "5s"


[env]
SERVER_PORT = "50051"
RUST_LOG = "info"

[deploy]
strategy = "immediate"

[processes]
web = "./fueldao-offchain-server"

[[services]]
internal_port = 50051
protocol = "tcp"
auto_start_machines = true
min_machines_running = 1

[[services.ports]]
handlers = ["tls"]
port = 443

[services.concurrency]
hard_limit = 1000
soft_limit = 500

[metrics]
port = 9090

