name: build-check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Canister Test Suite
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Cache install Nix packages
        uses: rikhuijzer/cache-install@v1.1.4
        with:
          key: nix-${{ hashFiles('default.nix') }}

      - name: Cache rust dependencies, build output, and DFX build cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
            .dfx/
          key: rust-test-${{ hashFiles('**/Cargo.lock') }}

      # - name: Lint check
      #   run: |
      #     nix-shell --pure -p rustup --run "
      #       cargo fmt --check
      #       cargo clippy --no-deps --all-features --release -- -D warnings
      #     "

      - name: Build
        run: |
          nix-shell --pure -p rustup musl gcc --run "
            cargo build --release --target x86_64-unknown-linux-musl
          "

      - name: Run Canister Test Suite
        env:
          POCKET_IC_BIN: ${{ github.workspace }}/pocket-ic
        run: nix-shell --run "cargo test"

      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: build-musl
          path: |
            $(find target/x86_64-unknown-linux-musl/release -type f -name '*')
