name: Deploy to Fly.io

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  FLY_API_TOKEN: ${{ secrets.FLY_IO_DEPLOY_TOKEN }}
  FLY_ORG: "fuel" # Add your organization slug here

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Create Fly.io App
        run: |
          flyctl apps create fuel-dao-offchain -o $FLY_ORG || echo "App already exists"

      - name: Verify App Existence
        run: flyctl apps list

      - name: Deploy to Fly.io
        run: flyctl deploy -a fuel-dao-offchain -o $FLY_ORG # Specify the app name and organization slug here

