name: Deploy to Fly.io on Push or PR to Main

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_check:
    name: Build and Check
    uses: ./.github/workflows/build-check.yml
    with:
      publish-artifact: true

  deploy:
    name: Deploy
    needs: build_check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: build-musl

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy to Fly.io
        run: |
          flyctl deploy --remote-only --build-target $(find target/x86_64-unknown-linux-musl/release -type f -name '*')
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_DEPLOY_TOKEN }}
