name: Deploy to Fly.io on Push or PR to Main

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Create Fly.io App
        run: |
          flyctl apps create fuel-dao-offchain || echo "App already exists"

      - name: Set environment secrets
        run: |
          flyctl secrets set BACKEND="${{ secrets.BACKEND }}" --app "fuel-dao-offchain"
          flyctl secrets set RUST_LOG="${{ secrets.RUST_LOG }}" --app "fuel-dao-offchain"
          flyctl secrets set SERVER_PORT="${{ secrets.SERVER_PORT }}" --app "fuel-dao-offchain"
          flyctl secrets set EMAIL_CLIENT_ID="${{ secrets.EMAIL_CLIENT_ID }}" --app "fuel-dao-offchain"
          flyctl secrets set EMAIL_CLIENT_SECRET="${{ secrets.EMAIL_CLIENT_SECRET }}" --app "fuel-dao-offchain"
          flyctl secrets set EMAIL_ACCESS_TOKEN="${{ secrets.EMAIL_ACCESS_TOKEN }}" --app "fuel-dao-offchain"
          flyctl secrets set EMAIL_REFRESH_TOKEN="${{ secrets.EMAIL_REFRESH_TOKEN }}" --app "fuel-dao-offchain"
        env:
          FLY_IO_DEPLOY_TOKEN: ${{ secrets.FLY_IO_DEPLOY_TOKEN }}

      - name: Deploy to Fly.io
        run: |
          flyctl deploy --remote-only
        env:
          FLY_IO_DEPLOY_TOKEN: ${{ secrets.FLY_IO_DEPLOY_TOKEN }}
