name: Deploy to Fly.io

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main



env:
  FLY_IO_DEPLOY_TOKEN: ${{ secrets.FLY_IO_DEPLOY_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Create Fly.io App (if not exists)
        run: |
          flyctl apps create fueldao-offchain-server --org fuel-dao || echo "App already exists, skipping creation"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_DEPLOY_TOKEN }}


      - uses: superfly/flyctl-actions/setup-flyctl@master
      - name: Deploy a docker container to fly.io
        run: flyctl deploy --remote-only --depot=false -a "fueldao-offchain-server"
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_DEPLOY_TOKEN }}
 # Specify the app name here