name: Deploy to Fly.io on Push or PR to Main

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  FLY_API_TOKEN: ${{ secrets.FLY_IO_DEPLOY_TOKEN }}

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - run: flyctl deploy --remote-onlyFLY_IO_DEPLOY_TOKEN }}
