name: Fly Deploy

on:
  push:
    branches:
      - main    # change to main if needed

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    concurrency: deploy-group    # optional: ensure only one action runs at a time

    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      # Set secrets before deploying
      - name: Set Fly secrets
        run: |
          flyctl secrets set EMAIL_REFRESH_TOKEN=${{ secrets.BOOKINGS_AT_FUEL_DAO_IO_GMAIL_ACCOUNT_REFRESH_TOKEN }} --app "fueldao-offchain-server" --stage
          flyctl secrets set EMAIL_CLIENT_SECRET=${{ secrets.GMAIL_OAUTH_CLIENT_SECRET_KEY }} --app "fueldao-offchain-server" --stage
          flyctl secrets set EMAIL_CLIENT_ID="462267493875-qe8r7afhg2gnto5pgdjfoquonel5oka2.apps.googleusercontent.com" --app "fueldao-offchain-server" --stage
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_DEPLOY_TOKEN }}
          
      - name: Deploy to Fly
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_IO_DEPLOY_TOKEN }}
